Plants api
SMS-Sajadi/Green-Garden-Back-Dev pull request #5
Opened 2023-05-26 16:58 UTC by SMS-Sajadi

Finally we have the homepage api, enjoy it

2023-05-26 19:32 UTC, mohamad-khorsandi requested changes

2023-05-26 19:32 UTC, mohamad-khorsandi commented on home/views.py
> +class ExploreAPI(ListAPIView):
نظرت چیه که اسم اینو عوض کنیم؟
یجوری که گویا ی کاری که انجام میشه باشه
داره لیست گل ها رو فیلتر میکنه برمیگردونه
plantFilterApi
مثلا

2023-05-26 20:31 UTC, SMS-Sajadi commented on home/views.py
> +class ExploreAPI(ListAPIView):
توافق مذاکرات😂

2023-05-27 11:14 UTC, mohamad-khorsandi commented on home/views.py
> +class ExploreAPI(ListAPIView):
کفایت مذاکرات joy

2023-05-27 11:35 UTC, mohamad-khorsandi approved these changes

2023-05-27 11:37 UTC, merged